#
# Based on official ElasticSearch Dockerfile
# https://github.com/dockerfile/elasticsearch
#

FROM dockerfile/java:oracle-java8

ENV ES_PKG_NAME elasticsearch-1.4.4

# Install ElasticSearch.
RUN \
  cd / && \
  wget https://download.elasticsearch.org/elasticsearch/elasticsearch/$ES_PKG_NAME.tar.gz && \
  tar xvzf $ES_PKG_NAME.tar.gz && \
  rm -f $ES_PKG_NAME.tar.gz && \
  mv /$ES_PKG_NAME /elasticsearch

# Mount elasticsearch.yml config
COPY elasticsearch.yml /elasticsearch/config/elasticsearch.yml

# Define default command.
CMD ["/elasticsearch/bin/elasticsearch"]

# Expose ports.
#   - 9200: HTTP
#   - 9300: transport
EXPOSE 9200
EXPOSE 9300